apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-actions-runner.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "github-actions-runner.name" . }}
    helm.sh/chart: {{ include "github-actions-runner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "github-actions-runner.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "github-actions-runner.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: GITHUB_REPO
            value: {{ .Values.runner.github.repo }}
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "github-actions-runner.fullname" . }}
                key: github_token
          - name: RUNNER_NAME
            value: {{ .Values.runner.name | default (include "github-actions-runner.fullname" .) }}
          - name: RUNNER_LABELS
            value: {{ .Values.runner.labels }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
