apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "github-actions-runner.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "github-actions-runner.name" . }}
    helm.sh/chart: {{ include "github-actions-runner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  github_token: {{ .Values.runner.github.token | b64enc | quote }}
